// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { SocialRecovery$Type } from "./SocialRecovery";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SocialRecovery"]: SocialRecovery$Type;
    ["contracts/SocialRecovery.sol:SocialRecovery"]: SocialRecovery$Type;
  }
}
