[package]
name = "agg_agg"
type = "bin"
authors = [""]
compiler_version = ">=0.36.0"

[package.metadata.generate_fixtures]
recursive = true

[[package.metadata.generate_fixtures.hash_updates]]
path = "../agg_final/src/main.nr"
kind = "global_field"
name = "AGG_AGG_VERIFICATION_KEY_HASH"

[dependencies]
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
