// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { HonkVerifier$Type } from "./HonkVerifier";
import { IVerifier$Type } from "./IVerifier";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["HonkVerifier"]: HonkVerifier$Type;
    ["IVerifier"]: IVerifier$Type;
    ["contracts/NoopVerifierHonk.sol:HonkVerifier"]: HonkVerifier$Type;
    ["contracts/NoopVerifierHonk.sol:IVerifier"]: IVerifier$Type;
  }
}
