[package]
name = "payy-evm-client-prover-bb"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
barretenberg-interface = { workspace = true }
contextful = { workspace = true }
element = { workspace = true }
payy-evm-client-prover-interface = { workspace = true }
zk-circuits = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
