// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { RollupV1$Type } from "./RollupV1";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RollupV1"]: RollupV1$Type;
    ["contracts/rollup/RollupV1.sol:RollupV1"]: RollupV1$Type;
  }
}
