use element::Element;
use serde::{Deserialize, Serialize};
#[cfg(feature = "ts-rs")]
use ts_rs::TS;

mod note_url;
mod parse;

pub use note_url::{
    NoteURLPayload, NoteUrlDecodeError, NoteUrlDecodeResult, decode_activity_url_payload,
    try_decode_activity_url_payload,
};
pub use parse::{ParseError, extract_invite_code, extract_memo, parse_send_url, parse_url};

/// Represents any supported Payy link.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[cfg_attr(feature = "ts-rs", derive(TS))]
#[cfg_attr(feature = "ts-rs", ts(export))]
#[cfg_attr(feature = "ts-rs", ts(rename = "PaymentLink"))]
#[serde(tag = "kind", rename_all = "kebab-case")]
pub enum Link {
    Request(RequestLink),
    Send(SendLinkHash),
    Invite(InviteLink),
}

/// Convenience alias for callers expecting the previous `PaymentLink` terminology.
pub type PaymentLink = Link;

/// Convenience enum for send-only link parsing operations.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[cfg_attr(feature = "ts-rs", derive(TS))]
#[cfg_attr(feature = "ts-rs", ts(export))]
#[serde(tag = "kind", rename_all = "kebab-case")]
pub enum SendLink {
    Send(SendLinkHash),
}

/// Request links generated by the v1 format `/r/1/<value>/<memo?>#<public_key>/<invite_code?>`.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts-rs", derive(TS))]
#[cfg_attr(feature = "ts-rs", ts(export))]
pub struct RequestLink {
    pub value: Element,
    pub public_key: Element,
    pub invite_code: Option<String>,
    pub memo: Option<String>,
}

/// `/s/<memo?>#<secret>` links containing a base58-encoded payload.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts-rs", derive(TS))]
#[cfg_attr(feature = "ts-rs", ts(export))]
pub struct SendLinkHash {
    pub secret_hash: String,
    pub memo: Option<String>,
}

/// `/invite/<code>` links for onboarding flows.
#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
#[cfg_attr(feature = "ts-rs", derive(TS))]
#[cfg_attr(feature = "ts-rs", ts(export))]
pub struct InviteLink {
    pub code: String,
}
