// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { TestRollupV1$Type } from "./TestRollupV1";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TestRollupV1"]: TestRollupV1$Type;
    ["contracts/mocks/TestRollupV1.sol:TestRollupV1"]: TestRollupV1$Type;
  }
}
