// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface TestRollupV1$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "TestRollupV1",
  "sourceName": "contracts/mocks/TestRollupV1.sol",
  "abi": [
    {
      "inputs": [],
      "stateMutability": "nonpayable",
      "type": "constructor"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "validFrom",
          "type": "uint256"
        },
        {
          "internalType": "address[]",
          "name": "validators",
          "type": "address[]"
        }
      ],
      "name": "setValidators",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],
  "bytecode": "0x6080806040523461001657610161908161001c8239f35b600080fdfe608080604052600436101561001357600080fd5b600090813560e01c63e795594d1461002a57600080fd5b346101275760403660031901126101275760043567ffffffffffffffff602435818111610123573660238201121561012357806004013591821161012357602490369260051b01011161011f5780159081156100f3575b501561008b575080f35b62461bcd60e51b815260206004820152603d60248201527f526f6c6c757056313a2076616c696446726f6d2063616e6e6f74206265206d6f60448201527f7265207468616e203330206461797320696e20746865206675747572650000006064820152608490fd5b905062278d0043019081431161010b57111538610081565b634e487b7160e01b84526011600452602484fd5b8280fd5b8480fd5b5080fdfea2646970667358221220779c814224cc88f0ac26bde1c217a37b705479eb6e037ba7bdc64d6b89880b0964736f6c63430008140033",
  "deployedBytecode": "0x608080604052600436101561001357600080fd5b600090813560e01c63e795594d1461002a57600080fd5b346101275760403660031901126101275760043567ffffffffffffffff602435818111610123573660238201121561012357806004013591821161012357602490369260051b01011161011f5780159081156100f3575b501561008b575080f35b62461bcd60e51b815260206004820152603d60248201527f526f6c6c757056313a2076616c696446726f6d2063616e6e6f74206265206d6f60448201527f7265207468616e203330206461797320696e20746865206675747572650000006064820152608490fd5b905062278d0043019081431161010b57111538610081565b634e487b7160e01b84526011600452602484fd5b8280fd5b8480fd5b5080fdfea2646970667358221220779c814224cc88f0ac26bde1c217a37b705479eb6e037ba7bdc64d6b89880b0964736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "TestRollupV1",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<TestRollupV1$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/mocks/TestRollupV1.sol:TestRollupV1",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<TestRollupV1$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "TestRollupV1",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<TestRollupV1$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/mocks/TestRollupV1.sol:TestRollupV1",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<TestRollupV1$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "TestRollupV1",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<TestRollupV1$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/mocks/TestRollupV1.sol:TestRollupV1",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<TestRollupV1$Type["abi"]>>;
}
