// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IVerifier$Type } from "./IVerifier";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IVerifier"]: IVerifier$Type;
    ["contracts/noir/IVerifier.sol:IVerifier"]: IVerifier$Type;
  }
}
