// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BoundsTestContract$Type } from "./BoundsTestContract";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BoundsTestContract"]: BoundsTestContract$Type;
    ["contracts/mocks/BoundsTestContract.sol:BoundsTestContract"]: BoundsTestContract$Type;
  }
}
