// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface BoundsTestContract$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "BoundsTestContract",
  "sourceName": "contracts/mocks/BoundsTestContract.sol",
  "abi": [
    {
      "inputs": [],
      "name": "getCurrentBlock",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getMaxAllowedValidFrom",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "getMaxFutureBlocks",
      "outputs": [
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "validFrom",
          "type": "uint256"
        }
      ],
      "name": "validateBounds",
      "outputs": [],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x60808060405234610016576101be908161001c8239f35b600080fdfe608080604052600436101561001357600080fd5b600090813560e01c9081630fdf57bc14610167575080634cbd355714610129578063672d5d3b1461010e5763db66a2291461004d57600080fd5b3461010b57602036600319011261010b5760043580159081156100df575b50156100745780f35b60405162461bcd60e51b815260206004820152603f60248201527f426f756e6473546573743a2076616c696446726f6d2063616e6e6f742062652060448201527f6d6f7265207468616e203330206461797320696e2074686520667574757265006064820152608490fd5b905062278d004301908143116100f75711153861006b565b634e487b7160e01b83526011600452602483fd5b80fd5b503461010b578060031936011261010b576020604051438152f35b503461010b578060031936011261010b5762278d0043019081431161015357602082604051908152f35b634e487b7160e01b81526011600452602490fd5b9050346101845781600319360112610184578062278d0060209252f35b5080fdfea2646970667358221220c896f410bd8a3062b47b8d4df4e45bd3cb41b5241795bcf6d96850a66302b6e464736f6c63430008140033",
  "deployedBytecode": "0x608080604052600436101561001357600080fd5b600090813560e01c9081630fdf57bc14610167575080634cbd355714610129578063672d5d3b1461010e5763db66a2291461004d57600080fd5b3461010b57602036600319011261010b5760043580159081156100df575b50156100745780f35b60405162461bcd60e51b815260206004820152603f60248201527f426f756e6473546573743a2076616c696446726f6d2063616e6e6f742062652060448201527f6d6f7265207468616e203330206461797320696e2074686520667574757265006064820152608490fd5b905062278d004301908143116100f75711153861006b565b634e487b7160e01b83526011600452602483fd5b80fd5b503461010b578060031936011261010b576020604051438152f35b503461010b578060031936011261010b5762278d0043019081431161015357602082604051908152f35b634e487b7160e01b81526011600452602490fd5b9050346101845781600319360112610184578062278d0060209252f35b5080fdfea2646970667358221220c896f410bd8a3062b47b8d4df4e45bd3cb41b5241795bcf6d96850a66302b6e464736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "BoundsTestContract",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BoundsTestContract$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/mocks/BoundsTestContract.sol:BoundsTestContract",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<BoundsTestContract$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "BoundsTestContract",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BoundsTestContract$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/mocks/BoundsTestContract.sol:BoundsTestContract",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<BoundsTestContract$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "BoundsTestContract",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BoundsTestContract$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/mocks/BoundsTestContract.sol:BoundsTestContract",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<BoundsTestContract$Type["abi"]>>;
}
