// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { RollupMigrationMock$Type } from "./RollupMigrationMock";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RollupMigrationMock"]: RollupMigrationMock$Type;
    ["contracts/mocks/RollupMigrationMock.sol:RollupMigrationMock"]: RollupMigrationMock$Type;
  }
}
