// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface RollupMigrationMock$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "RollupMigrationMock",
  "sourceName": "contracts/mocks/RollupMigrationMock.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "mint_hash",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "value",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "bytes32",
          "name": "note_kind",
          "type": "bytes32"
        }
      ],
      "name": "MintAdded",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "hash",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "bytes32",
          "name": "value",
          "type": "bytes32"
        },
        {
          "indexed": false,
          "internalType": "bytes32",
          "name": "note_kind",
          "type": "bytes32"
        }
      ],
      "name": "Minted",
      "type": "event"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "mint_hash",
          "type": "bytes32"
        },
        {
          "internalType": "uint256",
          "name": "value",
          "type": "uint256"
        },
        {
          "internalType": "bytes32",
          "name": "note_kind",
          "type": "bytes32"
        }
      ],
      "name": "emitMintAdded",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "hash",
          "type": "bytes32"
        },
        {
          "internalType": "bytes32",
          "name": "value",
          "type": "bytes32"
        },
        {
          "internalType": "bytes32",
          "name": "note_kind",
          "type": "bytes32"
        }
      ],
      "name": "emitMinted",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "hash",
          "type": "bytes32"
        }
      ],
      "name": "getMint",
      "outputs": [
        {
          "components": [
            {
              "internalType": "bytes32",
              "name": "note_kind",
              "type": "bytes32"
            },
            {
              "internalType": "uint256",
              "name": "amount",
              "type": "uint256"
            },
            {
              "internalType": "bool",
              "name": "spent",
              "type": "bool"
            }
          ],
          "internalType": "struct RollupMigrationMock.Mint",
          "name": "",
          "type": "tuple"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "mint_hash",
          "type": "bytes32"
        },
        {
          "internalType": "bytes32",
          "name": "value",
          "type": "bytes32"
        },
        {
          "internalType": "bytes32",
          "name": "note_kind",
          "type": "bytes32"
        }
      ],
      "name": "mint",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "name": "mints",
      "outputs": [
        {
          "internalType": "bytes32",
          "name": "note_kind",
          "type": "bytes32"
        },
        {
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        },
        {
          "internalType": "bool",
          "name": "spent",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x60808060405234610016576102c5908161001c8239f35b600080fdfe604060808152600436101561001357600080fd5b600090813560e01c8063059236d2146101f25780634eeb381e1461016957806356dc63cb14610125578063a2ce9c1f146100b15763df9bc5ad1461005657600080fd5b346100ad577f948ecd827e77afeeebdc95f4d34a294c53d7e28501dcd56c8d89e88e61b53a506100853661023a565b8286526020868152858720600201805460ff191660011790558551928352820152909290a280f35b5080fd5b50346100ad5760203660031901126100ad578082606093826100d1610259565b828152826020820152015260043581528060205220906100ef610259565b8254928382528260ff60026001840154936020860194855201541692019115158252825193845251602084015251151590820152f35b50346100ad5760203660031901126100ad5780606092600435815280602052209081549160ff60026001830154920154169082519384526020840152151590820152f35b50346100ad577fc4adcac6a89d730f3a6da5d846bba3d858a8fc5884e0f80940a3a3b96a4ae6f16101993661023a565b6101e46101a7959395610259565b828152600260208201858152868301908a8252898b528a602052878b209351845551600184015551151591019060ff801983541691151516179055565b82519182526020820152a280f35b50346100ad5760603660031901126100ad577fc4adcac6a89d730f3a6da5d846bba3d858a8fc5884e0f80940a3a3b96a4ae6f1600435916024356044356101e46101a7610259565b606090600319011261025457600435906024359060443590565b600080fd5b604051906060820182811067ffffffffffffffff82111761027957604052565b634e487b7160e01b600052604160045260246000fdfea2646970667358221220271435c0ecba7c405943457e753a7704b4092ec92b4e593f557011ff63780a9d64736f6c63430008140033",
  "deployedBytecode": "0x604060808152600436101561001357600080fd5b600090813560e01c8063059236d2146101f25780634eeb381e1461016957806356dc63cb14610125578063a2ce9c1f146100b15763df9bc5ad1461005657600080fd5b346100ad577f948ecd827e77afeeebdc95f4d34a294c53d7e28501dcd56c8d89e88e61b53a506100853661023a565b8286526020868152858720600201805460ff191660011790558551928352820152909290a280f35b5080fd5b50346100ad5760203660031901126100ad578082606093826100d1610259565b828152826020820152015260043581528060205220906100ef610259565b8254928382528260ff60026001840154936020860194855201541692019115158252825193845251602084015251151590820152f35b50346100ad5760203660031901126100ad5780606092600435815280602052209081549160ff60026001830154920154169082519384526020840152151590820152f35b50346100ad577fc4adcac6a89d730f3a6da5d846bba3d858a8fc5884e0f80940a3a3b96a4ae6f16101993661023a565b6101e46101a7959395610259565b828152600260208201858152868301908a8252898b528a602052878b209351845551600184015551151591019060ff801983541691151516179055565b82519182526020820152a280f35b50346100ad5760603660031901126100ad577fc4adcac6a89d730f3a6da5d846bba3d858a8fc5884e0f80940a3a3b96a4ae6f1600435916024356044356101e46101a7610259565b606090600319011261025457600435906024359060443590565b600080fd5b604051906060820182811067ffffffffffffffff82111761027957604052565b634e487b7160e01b600052604160045260246000fdfea2646970667358221220271435c0ecba7c405943457e753a7704b4092ec92b4e593f557011ff63780a9d64736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "RollupMigrationMock",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<RollupMigrationMock$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/mocks/RollupMigrationMock.sol:RollupMigrationMock",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<RollupMigrationMock$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "RollupMigrationMock",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<RollupMigrationMock$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/mocks/RollupMigrationMock.sol:RollupMigrationMock",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<RollupMigrationMock$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "RollupMigrationMock",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<RollupMigrationMock$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/mocks/RollupMigrationMock.sol:RollupMigrationMock",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<RollupMigrationMock$Type["abi"]>>;
}
