// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Eip7702SimpleAccount$Type } from "./Eip7702SimpleAccount";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Eip7702SimpleAccount"]: Eip7702SimpleAccount$Type;
    ["contracts/Eip7702SimpleAccount.sol:Eip7702SimpleAccount"]: Eip7702SimpleAccount$Type;
  }
}
