// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { LitActionRegistry$Type } from "./LitActionRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["LitActionRegistry"]: LitActionRegistry$Type;
    ["contracts/LitActionRegistry.sol:LitActionRegistry"]: LitActionRegistry$Type;
  }
}
