// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MockUSDC$Type } from "./MockUSDC";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockUSDC"]: MockUSDC$Type;
    ["contracts/mocks/MockUSDC.sol:MockUSDC"]: MockUSDC$Type;
  }
}
