[package]
name = "beam-cli"
version = "0.2.4"
edition = "2024"
publish = false

[[bin]]
name = "beam"
path = "src/main.rs"

[dependencies]
argon2 = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bip39 = { workspace = true }
clap = { workspace = true }
contextful = { workspace = true }
contracts = { workspace = true }
dirs = { workspace = true }
element = { workspace = true }
encrypt = { workspace = true }
eth-util = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
json-store = { workspace = true }
num-bigint = { workspace = true }
payy-evm-client = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
rlp = { workspace = true }
rpassword = { workspace = true }
rustyline = { workspace = true }
secp256k1 = { workspace = true }
self-replace = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
shlex = { workspace = true }
sha2 = { workspace = true }
sourcify-client-reqwest = { workspace = true }
sourcify-interface = { workspace = true }
thiserror = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
wasmi = { workspace = true }
web3 = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
mockito = { workspace = true }
serial_test = { workspace = true }

[features]
default = ["privacy-bb-cli"]
privacy-bb-cli = ["payy-evm-client/bb-cli"]
