// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MockVerifier$Type } from "./MockVerifier";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockVerifier"]: MockVerifier$Type;
    ["contracts/mocks/MockVerifier.sol:MockVerifier"]: MockVerifier$Type;
  }
}
