// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface MockVerifier$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "MockVerifier",
  "sourceName": "contracts/mocks/MockVerifier.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "bytes",
          "name": "proof",
          "type": "bytes"
        },
        {
          "internalType": "bytes32[]",
          "name": "publicInputs",
          "type": "bytes32[]"
        }
      ],
      "name": "verify",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "pure",
      "type": "function"
    }
  ],
  "bytecode": "0x608080604052346100155760e3908161001b8239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c63ea50d0e414602857600080fd5b34609d576040366003190112609d5767ffffffffffffffff60043581811160a1573660238201121560a157806004013582811160a9573691016024011160a55760243581811160a1573660238201121560a157806004013591821160a157602490369260051b010111609d5780600160209252f35b5080fd5b8380fd5b8280fd5b8480fdfea2646970667358221220546453462175785a0214661852d377fbfc6dcddac6b9a803594038f03a9bae7464736f6c63430008140033",
  "deployedBytecode": "0x6080806040526004361015601257600080fd5b600090813560e01c63ea50d0e414602857600080fd5b34609d576040366003190112609d5767ffffffffffffffff60043581811160a1573660238201121560a157806004013582811160a9573691016024011160a55760243581811160a1573660238201121560a157806004013591821160a157602490369260051b010111609d5780600160209252f35b5080fd5b8380fd5b8280fd5b8480fdfea2646970667358221220546453462175785a0214661852d377fbfc6dcddac6b9a803594038f03a9bae7464736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "MockVerifier",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<MockVerifier$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/mocks/MockVerifier.sol:MockVerifier",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<MockVerifier$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "MockVerifier",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<MockVerifier$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/mocks/MockVerifier.sol:MockVerifier",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<MockVerifier$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "MockVerifier",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<MockVerifier$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/mocks/MockVerifier.sol:MockVerifier",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<MockVerifier$Type["abi"]>>;
}
