CREATE TABLE notes (
    id UUID PRIMARY KEY,
    address BPCHAR(64) NOT NULL,
    private_key BPCHAR(64) NOT NULL,
    psi BPCHAR(64) NOT NULL,
    value NUMERIC NOT NULL,
    owner_id UUID NOT NULL,
    status TEXT NOT NULL,
    parent_1_id UUID,
    received_ref_kind TEXT,
    received_ref_id TEXT,
    spent_at TIMESTAMPTZ,
    added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    commitment BPCHAR(64) NOT NULL,
    spend_ref_kind TEXT,
    spend_ref_id TEXT,
    parent_2_id UUID,
    version SMALLINT NOT NULL DEFAULT 0,
    kind BPCHAR(64) NOT NULL DEFAULT '0000000000000000000000000000000000000000000000000000000000000001'
);

CREATE TABLE ramps_transactions (
    id UUID PRIMARY KEY,
    address BPCHAR(64),
    provider TEXT NOT NULL,
    account_id UUID NOT NULL,
    external_id TEXT,
    external_fund_id TEXT,
    quote_id UUID,
    status TEXT NOT NULL,
    from_currency TEXT NOT NULL,
    from_amount NUMERIC NOT NULL,
    from_network TEXT NOT NULL,
    from_network_identifier JSONB,
    to_currency TEXT NOT NULL,
    to_amount NUMERIC NOT NULL,
    to_network TEXT NOT NULL,
    to_network_identifier JSONB,
    evm_address TEXT,
    name TEXT,
    memo TEXT,
    "desc" TEXT,
    emoji TEXT,
    category TEXT NOT NULL,
    metadata JSONB,
    transaction_at TIMESTAMPTZ,
    added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    icon TEXT,
    pending_refund_amount NUMERIC,
    funding_status TEXT,
    funding_due_amount NUMERIC,
    wallet_id UUID NOT NULL,
    status_reason TEXT,
    private_key TEXT,
    local_id TEXT,
    funding_kind TEXT NOT NULL,
    from_note_kind TEXT,
    to_note_kind TEXT
);
