// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BalanceMovement } from "./BalanceMovement";
import type { BungeeDepositExternal } from "./BungeeDepositExternal";
import type { BurnExternal } from "./BurnExternal";
import type { CardExternal } from "./CardExternal";
import type { ClaimLinkExternal } from "./ClaimLinkExternal";
import type { MintExternal } from "./MintExternal";
import type { NoExternalData } from "./NoExternalData";
import type { RampDepositExternal } from "./RampDepositExternal";
import type { RampWithdrawExternal } from "./RampWithdrawExternal";
import type { SendLinkExternal } from "./SendLinkExternal";
import type { SendRegistryExternal } from "./SendRegistryExternal";
import type { SupportExternal } from "./SupportExternal";
import type { WorkerStatus } from "./WorkerStatus";

export type ActivityExternalData =
  & {
    /**
     * ID of the activity
     */
    id: string;
    /**
     * Title for the activity
     */
    title: string;
    /**
     * Secondary info
     */
    subtitle: string | null;
    /**
     * Display amount
     */
    display_amount: string | null;
    /**
     * Display status, status infomation to display to the user
     */
    display_status: string;
    /**
     * Strikethrough
     */
    strikethrough: boolean;
    /**
     * Balance movement (affect on the balance of a given token)
     */
    balance_movement: BalanceMovement | null;
    /**
     * Is the activity in a CTA (call to action) state, that means it should
     * be highlighted and pinned
     */
    is_cta: boolean;
    /**
     * Worker status
     */
    worker_status: WorkerStatus;
    /**
     * The alert count number to show for the activity item to signify
     * new events have occured
     */
    alert_count: number;
    /**
     * Added at date
     */
    timestamp: string;
  }
  & (
    | { "kind": "KYC_V1"; "data": NoExternalData }
    | { "kind": "SEND_LINK_V1"; "data": SendLinkExternal }
    | { "kind": "CLAIM_LINK_V1"; "data": ClaimLinkExternal }
    | { "kind": "SEND_REGISTRY_V1"; "data": SendRegistryExternal }
    | { "kind": "CARD_V1"; "data": CardExternal }
    | { "kind": "MINT_V1"; "data": MintExternal }
    | { "kind": "BURN_V1"; "data": BurnExternal }
    | { "kind": "RAMP_DEPOSIT_V1"; "data": RampDepositExternal }
    | { "kind": "RAMP_DEPOSIT_LINK_V1"; "data": NoExternalData }
    | { "kind": "RAMP_WITHDRAW_V1"; "data": RampWithdrawExternal }
    | { "kind": "SUPPORT_V1"; "data": SupportExternal }
    | { "kind": "MIGRATE_V0"; "data": NoExternalData }
    | { "kind": "WALLET_V0"; "data": NoExternalData }
    | { "kind": "ACROSS_DEPOSIT"; "data": NoExternalData }
    | { "kind": "BUNGEE_DEPOSIT_V1"; "data": BungeeDepositExternal }
  );
