// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityExternalData } from "./ActivityExternalData";
import type { ActivityStoreListQueryFilter } from "./ActivityStoreListQueryFilter";
import type { LoadingResult } from "./LoadingResult";

export type ActivityListViewModel = {
  /**
   * Whether the app/wallet is ready (gates all loading states).
   * When false, screen must show loading spinner regardless of activities state.
   */
  isReady: boolean;
  /**
   * Activity data with loading/error state. Uses LoadingResult from pkg/payy_core_types/src/loadable.rs.
   * - Loading: initial load in progress (or app not ready)
   * - Ok(vec): activities loaded (empty vec = no activities)
   * - Err(string): **UNUSED in this migration** - kept for forward compatibility only
   *
   * NOTE: Current source (useActivitiesListLongPoll) does not expose a typed error channel.
   * Container must never emit Err variant in this migration.
   */
  activities: LoadingResult<Array<ActivityExternalData>, string>;
  /**
   * Whether more activities are loading remotely (pagination footer spinner)
   */
  activitiesRemoteLoading: boolean;
  /**
   * Whether to show notification request banner
   */
  shouldShowNotification: boolean;
  /**
   * Whether notification request is in progress
   */
  notificationLoading: boolean;
  /**
   * Current filter selection
   */
  filter: ActivityStoreListQueryFilter;
  /**
   * Whether filter menu is open
   */
  filterMenuOpen: boolean;
  /**
   * Whether card transaction export is in progress
   */
  isExportingCardTransactions: boolean;
  /**
   * Whether user has card transactions (for export option)
   */
  hasCardTransactions: boolean;
  /**
   * Whether balance values are visible (for ActivityItem rendering)
   */
  isBalanceVisible: boolean;
  /**
   * One-shot signal: when true, screen scrolls list to top and dispatches OnScrollToTopHandled
   */
  scrollToTop: boolean;
};
