// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityStoreListQueryFilter } from "./ActivityStoreListQueryFilter";

export type ActivityStoreListQuery = {
  /**
   * Offset from the first item
   */
  offset: number;
  /**
   * Maximum activity items to return (defaults to 100, no maximum)
   */
  limit: number;
  /**
   * Activity filters
   */
  filter: ActivityStoreListQueryFilter;
};
