// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActivityDetailEvent =
  | { "type": "onContactSupport"; "payload": Record<string, never> }
  | { "type": "onCancelSendLink"; "payload": Record<string, never> }
  | { "type": "onShowQr"; "payload": { url: string } }
  | { "type": "onShareLink"; "payload": { url: string } }
  | { "type": "onCancelBurn"; "payload": Record<string, never> }
  | { "type": "onRetry"; "payload": Record<string, never> };
