// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityExternalData } from "./ActivityExternalData";

export type ActivityDetailViewModel = {
  /**
   * Activity data (null when loading or not found)
   */
  activity: ActivityExternalData | null;
  /**
   * Main chain explorer URL (e.g., polygonscan.com)
   */
  mainChainExplorerUrl: string | null;
  /**
   * Main chain display name (e.g., "Polygon")
   */
  mainChainName: string | null;
  /**
   * Whether the activity is retryable
   */
  isRetryable: boolean;
  /**
   * Whether balance values are visible
   */
  isBalanceVisible: boolean;
  /**
   * Loading state for cancel send link action
   */
  cancelSendLinkLoading: boolean;
  /**
   * Loading state for cancel burn action
   */
  cancelBurnLoading: boolean;
  /**
   * Loading state for retry action
   */
  retryLoading: boolean;
};
