// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityStoreListQueryFilter } from "./ActivityStoreListQueryFilter";

export type ActivityListEvent =
  | { "type": "onActivityPress"; "payload": { id: string } }
  | { "type": "onNotificationRequest"; "payload": Record<string, never> }
  | { "type": "onEndReached"; "payload": Record<string, never> }
  | {
    "type": "onSelectFilter";
    "payload": { filter: ActivityStoreListQueryFilter };
  }
  | { "type": "onClearFilter"; "payload": Record<string, never> }
  | { "type": "onOpenFilterMenu"; "payload": Record<string, never> }
  | { "type": "onCloseFilterMenu"; "payload": Record<string, never> }
  | { "type": "onExportCardTransactions"; "payload": Record<string, never> }
  | { "type": "onScrollToTopHandled"; "payload": Record<string, never> };
