// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KycState } from "./KycState";

export type AddressPostalCodeViewModel = {
  initialValue: string | null;
  kycState: KycState;
};
