// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressStateOption } from "./AddressStateOption";
import type { KycState } from "./KycState";

export type AddressStateViewModel = {
  states: Array<AddressStateOption>;
  label: string | null;
  initialValue: string | null;
  kycState: KycState;
};
