// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KycState } from "./KycState";

export type AddressCountryViewModel = {
  initialValue: string | null;
  allowedCountries: Array<string> | null;
  helperText: string | null;
  kycState: KycState;
};
