// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddressStateEvent = {
  "type": "onSubmit";
  "payload": { state: string };
} | { "type": "onStatePress"; "payload": Record<string, never> };
