// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdvancedViewModel = {
  shareDiagnosticsLoading: boolean;
  copyDepositKeyLoading: boolean;
  fraudWarningsEnabled: boolean;
  mainChainName: string;
  showDeleteAllData: boolean;
  deleteAllDataLoading: boolean;
  address: string | null;
  diagnosticsDialogVisible: boolean;
};
