// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdvancedEvent =
  | { "type": "onShareDiagnostics"; "payload": Record<string, never> }
  | { "type": "onNavigateToTerms"; "payload": Record<string, never> }
  | { "type": "onCopyDepositKey"; "payload": Record<string, never> }
  | { "type": "onToggleFraudWarnings"; "payload": { value: boolean } }
  | { "type": "onDeleteAllData"; "payload": Record<string, never> }
  | { "type": "onCopyAddress"; "payload": Record<string, never> }
  | { "type": "onDiagnosticsDialogClose"; "payload": Record<string, never> }
  | { "type": "onDiagnosticsDialogSubmit"; "payload": { message: string } };
