// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BalanceAction } from "./BalanceAction";
import type { Element } from "./Element";

export type BalanceMovement = {
  action: BalanceAction;
  value: Element;
  note_kind: Element;
};
