// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wrapper for `Vec<u8>` that (de)serializes to/from base64 strings.
 *
 * Using this type instead of raw `Vec<u8>` avoids sprinkling `#[serde(serialize_with = ...)]`
 * attributes throughout the codebase while preserving the JSON contract.
 */
export type Base64Bytes = string;
