// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockContent } from "./BlockContent";

/**
 * High-level block representation exposed over HTTP.
 */
export type Block = {
  /**
   * Content of the block.
   */
  content: BlockContent;
  /**
   * Validator signature for the block.
   */
  signature: string;
};
