// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockChainsChainName } from "./BlockChainsChainName";

export type BlockChainsEvent = {
  "type": "onSelectChain";
  "payload": { chain: BlockChainsChainName };
};
