// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockHeight } from "./BlockHeight";

/**
 * Header information for a block.
 */
export type BlockHeader = {
  /**
   * Height of the block.
   */
  height: BlockHeight;
  /**
   * Hash of the previous block.
   */
  last_block_hash: string;
  /**
   * Epoch identifier.
   */
  epoch_id: bigint;
  /**
   * Hash of the last finalized block.
   */
  last_final_block_hash: string;
  /**
   * Approvals collected for the block.
   */
  approvals: string[];
};
