// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockHeader } from "./BlockHeader";
import type { BlockState } from "./BlockState";

/**
 * Block content containing the header and state.
 */
export type BlockContent = {
  /**
   * Block header metadata.
   */
  header: BlockHeader;
  /**
   * Block state describing the transactions.
   */
  state: BlockState;
};
