// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";
import type { TxnWithInfo } from "./TxnWithInfo";

/**
 * State payload for the block.
 */
export type BlockState = {
  /**
   * Merkle root hash after executing this block.
   */
  root_hash: Element;
  /**
   * Transactions included in the block.
   */
  txns: Array<TxnWithInfo>;
};
