// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from "./Block";

/**
 * Block bundle with metadata returned by the node.
 */
export type BlockWithInfo = {
  /**
   * Block payload.
   */
  block: Block;
  /**
   * Hash of the block.
   */
  hash: string;
  /**
   * Timestamp provided by the node.
   */
  time: bigint;
};
