// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BungeeToken = {
  address: string;
  name: string;
  symbol: string;
  decimals: number;
  logo_uri?: string;
};
