// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BungeeTokenListEntry } from "./BungeeTokenListEntry";

export type BungeeTokenListOutput = { tokens: Array<BungeeTokenListEntry> };
