// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BungeeToken } from "./BungeeToken";

export type BungeeTokenListEntry = {
  chain_id: number;
  tokens: Array<BungeeToken>;
};
