// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BuyNftEvent = {
  "type": "onSelectAmount";
  "payload": { amount: number };
} | { "type": "onCancelProcessing"; "payload": Record<string, never> };
