// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CardKycSubmitViewModel = {
  title: string;
  description: string;
  progressValue: number;
  progressDuration: number;
};
