// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CardWaitListProgress = {
  current: number;
  total: number;
  percentage: number;
  formattedCurrent: string;
  formattedTotal: string;
};
