// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkIdentifier } from "./NetworkIdentifier";

/**
 * PromoCard domain state (excludes layout-derived width)
 */
export type CardPromoCardViewModel = {
  hidden: boolean;
  frozen: boolean;
  secrets: NetworkIdentifier | null;
  backgroundColor: string;
};
