// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CardShippingDetailsViewModel = {
  heading: string;
  nameLabel: string;
  streetLabel: string;
  cityLabel: string;
  postalCodeLabel: string;
  countryLabel: string;
  name: string;
  addressStreet: string;
  addressCity: string;
  addressPostalCode: string;
  addressCountry: string;
  submitLabel: string;
  isSubmitDisabled: boolean;
  isSubmitLoading: boolean;
};
