// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardEntryColorScheme } from "./CardEntryColorScheme";

export type CardEntryViewModel = {
  title: string;
  colorScheme: CardEntryColorScheme;
};
