// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CardShippingDetailsEvent =
  | { "type": "onChangeName"; "payload": { value: string } }
  | { "type": "onChangeAddressStreet"; "payload": { value: string } }
  | { "type": "onChangeAddressCity"; "payload": { value: string } }
  | { "type": "onChangeAddressPostalCode"; "payload": { value: string } }
  | { "type": "onChangeAddressCountry"; "payload": { value: string } }
  | { "type": "onPressAddressCountry"; "payload": Record<string, never> }
  | { "type": "onSubmit"; "payload": Record<string, never> };
