// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardTermsButtonColorScheme } from "./CardTermsButtonColorScheme";
import type { CardTermsCheckboxItem } from "./CardTermsCheckboxItem";

export type CardTermsViewModel = {
  title: string;
  checkboxes: Array<CardTermsCheckboxItem>;
  buttonLabel: string;
  buttonColorScheme: CardTermsButtonColorScheme;
  showArrow: boolean;
};
