// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardUsageInstructionStepViewModel } from "./CardUsageInstructionStepViewModel";

export type CardUsageInstructionsViewModel = {
  title: string;
  steps: Array<CardUsageInstructionStepViewModel>;
  show: boolean;
};
