// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardWaitListProgress } from "./CardWaitListProgress";
import type { CardWaitListVariant } from "./CardWaitListVariant";

export type CardWaitListViewModel = {
  variant: CardWaitListVariant;
  title: string;
  description: string;
  buttonText: string | null;
  showProgress: boolean;
  progress: CardWaitListProgress | null;
};
