// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CardTermsEvent =
  | { "type": "onCheckboxToggle"; "payload": { id: string } }
  | { "type": "onLinkPress"; "payload": { url: string } }
  | { "type": "onAccept"; "payload": Record<string, never> };
