// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CardTermsCheckboxItem = {
  id: string;
  title: string;
  linkUrl: string | null;
  linkLabel: string | null;
  acknowledgementText: string | null;
  checked: boolean;
  showGlbaDisclosure: boolean | null;
  glbaDisclosureUrl: string | null;
  glbaDisclosureLabel: string | null;
};
