// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CardPinEntryEvent = {
  "type": "onKeyboardChange";
  "payload": { value: string };
} | { "type": "onPrimaryAction"; "payload": Record<string, never> };
