// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardOnboardingWaitListVariant } from "./CardOnboardingWaitListVariant";

export type CardOnboardingViewModel = {
  applyButtonLabel: string;
  applyButtonSubLabel: string;
  isArgentina: boolean;
  waitlistVariant: CardOnboardingWaitListVariant;
  waitlistTitle: string;
  waitlistDescription: string;
};
