// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardDetailItemViewModel } from "./CardDetailItemViewModel";
import type { CardFreezeActionViewModel } from "./CardFreezeActionViewModel";
import type { CardPinViewModel } from "./CardPinViewModel";
import type { CardPromoCardViewModel } from "./CardPromoCardViewModel";
import type { CardUsageInstructionsViewModel } from "./CardUsageInstructionsViewModel";
import type { CardWaitListViewModel } from "./CardWaitListViewModel";

export type CardViewModel = {
  promoCard: CardPromoCardViewModel;
  hidden: boolean;
  viewLabel: string;
  hideLabel: string;
  toggleHiddenLoading: boolean;
  freezeAction: CardFreezeActionViewModel;
  hasBalance: boolean;
  details: Array<CardDetailItemViewModel>;
  pin: CardPinViewModel;
  usageInstructions: CardUsageInstructionsViewModel;
  isArgentina: boolean;
  waitList: CardWaitListViewModel | null;
};
