// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CardEvent =
  | { "type": "onToggleHidden"; "payload": Record<string, never> }
  | { "type": "onFreezeAction"; "payload": Record<string, never> }
  | { "type": "onCopyDetail"; "payload": { index: number } }
  | { "type": "onChangePin"; "payload": Record<string, never> }
  | { "type": "onWaitListButtonPress"; "payload": Record<string, never> };
