// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CardPinEntryViewModel = {
  title: string;
  instruction: string;
  pinLength: number;
  currentPin: string;
  errorMessage: string | null;
  keyboardKey: number;
  primaryActionLabel: string;
  primaryActionLoading: boolean;
  primaryActionDisabled: boolean;
  pinSymbol: string | null;
};
