// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardInstructionIconType } from "./CardInstructionIconType";

export type CardUsageInstructionStepViewModel = {
  text: string;
  iconType: CardInstructionIconType;
};
