// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CardPinViewModel = {
  label: string;
  display: string;
  changeLabel: string;
  canChange: boolean;
  errorMessage: string | null;
  showError: boolean;
};
