// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Category =
  | "BILLS"
  | "CHARITY"
  | "EATING_OUT"
  | "ENTERTAINMENT"
  | "EXPENSES"
  | "FAMILY"
  | "FINANCES"
  | "GENERAL"
  | "GIFTS"
  | "GROCERIES"
  | "HOLIDAYS"
  | "INCOME"
  | "PERSONAL_CARE"
  | "SAVINGS"
  | "SHOPPING"
  | "TRANSFER"
  | "TRANSPORT"
  | "PET_CARE";
