// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChainConfig = {
  chain_id: number;
  rpc_url: string;
  usdc_address: string;
  across_address: string;
  eip7702_simple_account_address: string;
  rollup_contract_address?: string;
};
