// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaimPaymentColorScheme } from "./ClaimPaymentColorScheme";
import type { ClaimPaymentNoteTitle } from "./ClaimPaymentNoteTitle";

export type ClaimPaymentViewModel = {
  canClaim: boolean;
  disabled: boolean;
  swipeTitle: string;
  swipeLabel: string;
  loadingLabel: string;
  doneLabel: string;
  swipeColorScheme: ClaimPaymentColorScheme;
  fallbackColorScheme: ClaimPaymentColorScheme;
  noteTitle: ClaimPaymentNoteTitle | null;
  fallbackTitle: ClaimPaymentNoteTitle | null;
  memoTextColor: string | null;
  /**
   * Serialized as string to support bigint; null when not available.
   */
  noteValue: string | null;
  memo: string | null;
  showInternetBanner: boolean;
};
