// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaimSource } from "./ClaimSource";

export type ClaimLinkExternal = {
  /**
   * Memo (optional)
   */
  memo: string | null;
  /**
   * Source of the claim (Link = claimed, Registry = received)
   */
  source: ClaimSource;
};
