// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaimPaymentNoteTitleSize } from "./ClaimPaymentNoteTitleSize";

export type ClaimPaymentNoteTitle = {
  lines: Array<string> | null;
  size: ClaimPaymentNoteTitleSize | null;
  color: string | null;
  subtitle: string | null;
  subtitleColor: string | null;
};
