// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Note } from "./Note";
import type { WalletPrivateKeyKind } from "./WalletPrivateKeyKind";

export type ClaimRegistryNoteInput = {
  note: Note;
  private_key_kind: WalletPrivateKeyKind;
  memo: string | null;
};
