// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";
import type { StoredNote } from "./StoredNote";

export type ClaimableNote = { note: StoredNote; secret_key: Element };
