// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressInput } from "./AddressInput";
import type { BurnInput } from "./BurnInput";
import type { CancelActivityInput } from "./CancelActivityInput";
import type { ClaimLinkInput } from "./ClaimLinkInput";
import type { ClaimRegistryNoteInput } from "./ClaimRegistryNoteInput";
import type { CommitmentInput } from "./CommitmentInput";
import type { CompressInput } from "./CompressInput";
import type { DecompressInput } from "./DecompressInput";
import type { GetActivityInput } from "./GetActivityInput";
import type { GetBalanceLongPollInput } from "./GetBalanceLongPollInput";
import type { GetBungeeTokenListInput } from "./GetBungeeTokenListInput";
import type { GetDepositPendingBalanceLongPollInput } from "./GetDepositPendingBalanceLongPollInput";
import type { GetMintBalanceInput } from "./GetMintBalanceInput";
import type { GetUnclaimedBalanceLongPollInput } from "./GetUnclaimedBalanceLongPollInput";
import type { ListActivityInput } from "./ListActivityInput";
import type { ListActivityLongPollInput } from "./ListActivityLongPollInput";
import type { LoadWalletInput } from "./LoadWalletInput";
import type { MigrateInput } from "./MigrateInput";
import type { MigrateProofInput } from "./MigrateProofInput";
import type { MintInput } from "./MintInput";
import type { OldAddressInput } from "./OldAddressInput";
import type { ParseLinkInput } from "./ParseLinkInput";
import type { ParseLinkSecretInput } from "./ParseLinkSecretInput";
import type { PayyCoreProcessEventInput } from "./PayyCoreProcessEventInput";
import type { PayyCoreViewModelLongPollInput } from "./PayyCoreViewModelLongPollInput";
import type { RetryActivityInput } from "./RetryActivityInput";
import type { SendLinkInput } from "./SendLinkInput";
import type { SendRegistryInput } from "./SendRegistryInput";
import type { SignInput } from "./SignInput";

export type Command =
  | { "cmd": "logs" }
  | { "cmd": "diagnostics" }
  | { "cmd": "load_wallet"; "params": LoadWalletInput }
  | { "cmd": "mint"; "params": MintInput }
  | { "cmd": "burn"; "params": BurnInput }
  | { "cmd": "send_link"; "params": SendLinkInput }
  | { "cmd": "send_registry"; "params": SendRegistryInput }
  | { "cmd": "claim_link"; "params": ClaimLinkInput }
  | { "cmd": "claim_registry_note"; "params": ClaimRegistryNoteInput }
  | { "cmd": "parse_link"; "params": ParseLinkInput }
  | { "cmd": "parse_link_secret"; "params": ParseLinkSecretInput }
  | { "cmd": "get_activity_alert_count" }
  | { "cmd": "get_activity"; "params": GetActivityInput }
  | { "cmd": "list_activity"; "params": ListActivityInput }
  | { "cmd": "list_activity_long_poll"; "params": ListActivityLongPollInput }
  | { "cmd": "cancel_activity"; "params": CancelActivityInput }
  | { "cmd": "retry_activity"; "params": RetryActivityInput }
  | { "cmd": "get_balance" }
  | { "cmd": "get_balance_long_poll"; "params": GetBalanceLongPollInput }
  | { "cmd": "get_deposit_pending_balance" }
  | {
    "cmd": "get_deposit_pending_balance_long_poll";
    "params": GetDepositPendingBalanceLongPollInput;
  }
  | { "cmd": "get_unclaimed_balance" }
  | {
    "cmd": "get_unclaimed_balance_long_poll";
    "params": GetUnclaimedBalanceLongPollInput;
  }
  | { "cmd": "get_mint_balance"; "params": GetMintBalanceInput }
  | { "cmd": "sign"; "params": SignInput }
  | { "cmd": "address"; "params": AddressInput }
  | { "cmd": "old_address"; "params": OldAddressInput }
  | { "cmd": "commitment"; "params": CommitmentInput }
  | { "cmd": "points" }
  | { "cmd": "compress"; "params": CompressInput }
  | { "cmd": "decompress"; "params": DecompressInput }
  | { "cmd": "migrate"; "params": MigrateInput }
  | { "cmd": "migrate_proof"; "params": MigrateProofInput }
  | { "cmd": "get_bungee_token_list"; "params": GetBungeeTokenListInput }
  | { "cmd": "payy_core_initialize" }
  | { "cmd": "payy_core_view_model" }
  | { "cmd": "payy_core_process_event"; "params": PayyCoreProcessEventInput }
  | { "cmd": "payy_core_reset" }
  | {
    "cmd": "payy_core_view_model_long_poll";
    "params": PayyCoreViewModelLongPollInput;
  };
