// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CountryEvent =
  | { "type": "onCountryChange"; "payload": { country: string } }
  | { "type": "onSubmit"; "payload": Record<string, never> }
  | { "type": "onCountryPress"; "payload": Record<string, never> };
