// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KycState } from "./KycState";

export type CountryViewModel = {
  title: string;
  country: string;
  allowedCountries: Array<string> | null;
  kycState: KycState;
};
