// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wire-format: variants serialize as exact PascalCase values to match existing runtime.
 * Do NOT use rename_all = "camelCase" on this enum - values must remain:
 * Binance, Robinhood, Coinbase, ByBit, Other
 */
export type CryptoExchangeKey =
  | "Binance"
  | "Robinhood"
  | "Coinbase"
  | "ByBit"
  | "Other";
