// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CryptoExchangeKey } from "./CryptoExchangeKey";

/**
 * Event contract: tagged union with { type, payload } format.
 * TS dispatch must always include payload: update({ type: 'onSelectExchange', payload: { key } })
 */
export type CryptoExchangesEvent = {
  "type": "onSelectExchange";
  "payload": { key: CryptoExchangeKey };
};
