// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DepositOptionKey } from "./DepositOptionKey";

export type DepositEvent = {
  "type": "onOptionPress";
  "payload": { key: DepositOptionKey };
};
