// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DepositOptionKey } from "./DepositOptionKey";

/**
 * Individual deposit option item (serializable only)
 * Note: Icon rendering happens in the screen based on `key`
 */
export type DepositOptionItemViewModel = {
  key: DepositOptionKey;
  title: string;
  description: string | null;
};
