// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DepositAddressViewModel = {
  heading: string;
  depositAddress: string | null;
  breakpoint: string;
  showMinDepositNotice: boolean;
  minDepositText: string;
  copyLabel: string;
};
