// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocKindOption } from "./DocKindOption";
import type { KycState } from "./KycState";

export type DocKindViewModel = {
  title: string;
  options: Array<DocKindOption>;
  selectedKind: string | null;
  kycState: KycState;
};
