// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DocScanEvent =
  | { "type": "onCapturePress"; "payload": Record<string, never> }
  | { "type": "onRequestCameraPermission"; "payload": Record<string, never> }
  | { "type": "onSubmit"; "payload": { imagePath: string } };
