// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A 256-bit unsigned integer
 *
 * This type is a wrapper around a [`U256`], so can represent any value in the range `0..=(2^256 -
 * 1)`.
 * However, in a ZK context, it is usually converted to a [`Base`], which is an integer modulo
 * "some large prime". This restricts the set of usable values to something approximating a `u254`
 *
 * [`Base`]: crate::Base
 */
export type Element = string;
