// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";

/**
 * Error data detailed the element related to the error
 */
export type ElementsVecData = {
  /**
   * Element related to error
   */
  elements: Array<Element>;
};
