// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FaceEvent = {
  "type": "onSubmit";
  "payload": {
    selfiefront: string | null;
    selfieleft: string | null;
    selfieright: string | null;
  };
};
