// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FaceRequiredField } from "./FaceRequiredField";
import type { KycState } from "./KycState";

export type FaceViewModel = {
  requiredFields: Array<FaceRequiredField>;
  kycState: KycState;
};
