// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlagsOption } from "./FlagsOption";
import type { KycState } from "./KycState";

export type FlagsViewModel = {
  flags: Array<FlagsOption>;
  submitDisabled: boolean;
  warningMessage: string | null;
  kycState: KycState;
};
