// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FraudWarningViewModel = {
  title: string;
  titleHighlight: string | null;
  calloutText: string;
  description: string;
  buttonLabel: string;
};
