// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Event variants for FulfillRequestScreen actions.
 */
export type FulfillRequestEvent =
  | { "type": "onSwipeUp"; "payload": Record<string, never> }
  | { "type": "onDone"; "payload": Record<string, never> }
  | { "type": "onClose"; "payload": Record<string, never> };
