// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FulfillRequestSwipeColorScheme } from "./FulfillRequestSwipeColorScheme";

/**
 * ViewModel for FulfillRequestScreen.
 */
export type FulfillRequestViewModel = {
  /**
   * Value as string to support bigint serialization.
   */
  value: string;
  memo: string | null;
  title: string;
  swipeLabel: string | null;
  loadingLabel: string;
  doneLabel: string;
  swipeColorScheme: FulfillRequestSwipeColorScheme;
  disabled: boolean;
  showInternetBanner: boolean;
};
