// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Color scheme for the swipe component.
 */
export type FulfillRequestSwipeColorScheme = "brand" | "dark";
