// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FundingStatus =
  | "PENDING_DEBIT"
  | "PENDING_CREDIT"
  | "INSUFFICIENT_FUNDS"
  | "SETTLED";
