// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetBalanceLongPollInput = {
  last_modified: string | null;
  timeout_secs: number | null;
};
