// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WalletPrivateKeyKind } from "./WalletPrivateKeyKind";

export type GetMintBalanceInput = { private_key_kind: WalletPrivateKeyKind };
