// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GuardianLoginItem = {
  id: string;
  displayName: string;
  iconName: string;
};
