// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Events emitted by the GuardianBackupScreen
 */
export type GuardianBackupEvent =
  | { "type": "onSelectEmptySlot"; "payload": Record<string, never> }
  | { "type": "onPressAddGuardian"; "payload": Record<string, never> }
  | { "type": "onPressGuardian"; "payload": { guardianId: string } };
