// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GuardianBackupIntroEvent = {
  "type": "onSelectCreate";
  "payload": Record<string, never>;
} | { "type": "onSelectRecover"; "payload": Record<string, never> };
