// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a single guardian slot in the backup screen UI
 */
export type GuardianBackupSlot = {
  id: string;
  displayName: string;
  iconName: string;
  number: number;
};
