// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuardianLoginItem } from "./GuardianLoginItem";

export type GuardianLoginViewModel = {
  title: string;
  guardians: Array<GuardianLoginItem>;
};
