// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuardianBackupSlot } from "./GuardianBackupSlot";

/**
 * ViewModel for the GuardianBackupScreen
 */
export type GuardianBackupViewModel = {
  guardians: Array<GuardianBackupSlot>;
  placeholderName: string;
  remainingSlots: number;
  filledStrengthCount: number;
  requiredGuardians: number;
  addGuardianLabel: string;
};
