// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GuardianBackupIntroViewModel = {
  description: string;
  createTitle: string;
  createSubtitle: string;
  recoverTitle: string;
  recoverSubtitle: string;
};
