// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HomeTabIconKind } from "./HomeTabIconKind";
import type { HomeTabKey } from "./HomeTabKey";
import type { HomeTabsStatusBarStyle } from "./HomeTabsStatusBarStyle";

export type HomeTabItemViewModel = {
  key: HomeTabKey;
  titleKey: string;
  bg: string;
  text: string;
  tabBg: string;
  tabText: string;
  statusBarStyle: HomeTabsStatusBarStyle;
  icon: HomeTabIconKind | null;
  tabFlex: number | null;
};
