// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HomeTabsEvent =
  | { "type": "onTabPress"; "payload": { index: number } }
  | { "type": "onPageSelected"; "payload": { index: number } }
  | { "type": "onRewardsPress"; "payload": Record<string, never> };
