// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HomeTabItemViewModel } from "./HomeTabItemViewModel";
import type { HomeTabsRewardsViewModel } from "./HomeTabsRewardsViewModel";

export type HomeTabsViewModel = {
  selectedIndex: number;
  tabs: Array<HomeTabItemViewModel>;
  activityAlertCount: number;
  scrollToTop: boolean;
  rewards: HomeTabsRewardsViewModel;
};
