// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";
import type { MerklePath } from "./MerklePath";
import type { WalletDataNote } from "./WalletDataNote";

export type InputNote = {
  note: WalletDataNote;
  secret_key: Element;
  merkle_path: MerklePath;
};
