// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvestOptionKey } from "./InvestOptionKey";

export type InvestEvent = {
  "type": "onPressInvestOption";
  "payload": { key: InvestOptionKey };
};
