// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadingResult } from "./LoadingResult";

export type InvestViewModel = {
  portfolioBalance: LoadingResult<string | null, string>;
  allTimeGains: LoadingResult<string | null, string>;
};
