// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KycField =
  | "firstname"
  | "middlename"
  | "lastname"
  | "dob"
  | "occupation"
  | "addressstreet"
  | "addresscity"
  | "addressstate"
  | "addresscountry"
  | "addresspostalcode"
  | "nationalities"
  | "documents"
  | "phone"
  | "phoneverified"
  | "email"
  | "emailverified"
  | "nationalid"
  | "civilstate"
  | "pep"
  | "fatca"
  | "uif";
