// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KycReviewStackNotificationBanner } from "./KycReviewStackNotificationBanner";
import type { KycReviewStatus } from "./KycReviewStatus";
import type { KycUpdateRequired } from "./KycUpdateRequired";

export type KycReviewStackViewModel = {
  status: KycReviewStatus;
  updateRequired: KycUpdateRequired | null;
  notificationBanner: KycReviewStackNotificationBanner | null;
  showApprovedButton: boolean;
};
