// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KycUpdateRequiredInvalidFields } from "./KycUpdateRequiredInvalidFields";

export type KycUpdateRequired =
  | { "error": "NONE" }
  | { "error": "UNSUPPORTED_COUNTRY" }
  | { "error": "INVALID_FIELDS"; "data": KycUpdateRequiredInvalidFields }
  | { "error": "USER_REQUESTED_DELETE" }
  | { "error": "PAYY_COMPLIANCE_VIOLATION" }
  | { "error": "DUPLICATE" }
  | { "error": "AGE_RESTRICTION" }
  | { "error": "DOCUMENT_FORGERY" }
  | { "error": "INVALID_DOCUMENT_PHOTO" }
  | { "error": "INCONSISTENT_DOCUMENTS" };
