// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KycField } from "./KycField";
import type { KycUpdateRequiredInvalidFieldsReason } from "./KycUpdateRequiredInvalidFieldsReason";

export type KycUpdateRequiredInvalidFields = {
  fields: { [key in KycField]?: KycUpdateRequiredInvalidFieldsReason };
};
