// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ListTxnsOrder } from "./ListTxnsOrder";

/**
 * Parameters for listing transactions.
 */
export type ListTxnsParams = {
  /**
   * Maximum number of transactions to return.
   */
  limit: number;
  /**
   * Pagination cursor for fetching additional transactions.
   */
  cursor?: string;
  /**
   * Ordering for the listed transactions.
   */
  order: ListTxnsOrder;
  /**
   * Whether to wait for a new transaction when none are available.
   */
  poll: boolean;
};
