// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockHeight } from "./BlockHeight";

/**
 * Cursor position for listing transactions.
 */
export type ListTxnsPosition = {
  /**
   * Block height for the transaction.
   */
  block: BlockHeight;
  /**
   * Transaction index within the block.
   */
  txn: bigint;
};
