// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityStoreListQuery } from "./ActivityStoreListQuery";

export type ListActivityInput = { query: ActivityStoreListQuery };
