// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityStoreListQuery } from "./ActivityStoreListQuery";

export type ListActivityLongPollInput = {
  query: ActivityStoreListQuery;
  last_modified: string | null;
  timeout_secs: number | null;
};
