// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ordering options for listing transactions.
 */
export type ListTxnsOrder = "NewestToOldest" | "OldestToNewest";
