// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TxnWithInfo } from "./TxnWithInfo";

/**
 * Response structure for listing transactions.
 */
export type ListTxnsResponse = {
  /**
   * Transactions returned by the node.
   */
  txns: Array<TxnWithInfo>;
  /**
   * Pagination cursor for fetching additional transactions.
   */
  cursor: import("./OpaqueClientCursor").OpaqueClientCursor;
};
