// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityExternalData } from "./ActivityExternalData";

export type ListActivityLongPollOutput = {
  data: Array<ActivityExternalData>;
  loading: boolean;
  last_modified: string;
};
