// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockWithInfo } from "./BlockWithInfo";

/**
 * Response structure for listing blocks.
 */
export type ListBlocksResponse = {
  /**
   * Blocks returned by the node.
   */
  blocks: Array<BlockWithInfo>;
  /**
   * Pagination cursor for fetching additional blocks.
   */
  cursor: import("./OpaqueClientCursor").OpaqueClientCursor;
};
