// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";
import type { MigrateInput } from "./MigrateInput";
import type { WalletMobileConfig } from "./WalletMobileConfig";

export type LoadWalletInput = {
  private_key: Element;
  config: WalletMobileConfig;
  force: boolean;
  locale: string | null;
  dsn: string;
  env_name: string;
  sentry_app_version: string;
  migration_data: MigrateInput | null;
};
