// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MenuItemKey } from "./MenuItemKey";

export type MenuEvent = {
  "type": "onItemPress";
  "payload": { key: MenuItemKey };
};
