// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MigratePublicInput } from "./MigratePublicInput";
import type { ProofBytes } from "./ProofBytes";

/**
 * Migration proof output
 */
export type MigrateProof = {
  /**
   * The proof bytes (without public inputs)
   */
  proof: ProofBytes;
  /**
   * The public inputs
   */
  public_inputs: MigratePublicInput;
};
