// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";

export type MigrateInputNote = {
  value: Element;
  address: Element;
  psi: Element;
  private_key: Element;
};
