// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Migration public inputs
 */
export type MigratePublicInput = {
  /**
   * The old address being migrated from
   */
  old_address: string;
  /**
   * The new address being migrated to
   */
  new_address: string;
};
