// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MigrateInputNote } from "./MigrateInputNote";

export type MigrateInput = {
  migration_id?: string;
  old_wallet_state?: string;
  notes?: Array<MigrateInputNote>;
};
