// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionResponse } from "./TransactionResponse";

/**
 * External mint data
 */
export type MintExternal = {
  /**
   * Hex address the mint was deposited from
   */
  evm_deposit_addr: string;
  /**
   * Evm txn hash where the deposit was sent
   */
  evm_txn_hash: string;
  /**
   * Payy txn receipt
   */
  txn_receipt: TransactionResponse | null;
};
