// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KycState } from "./KycState";
import type { NationalIdInputConfig } from "./NationalIdInputConfig";

export type NationalIdViewModel = {
  initialValue: string | null;
  inputConfig: NationalIdInputConfig | null;
  titleOverride: string | null;
  descriptionOverride: string | null;
  kycState: KycState;
};
