// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NationalIdInputRule } from "./NationalIdInputRule";

export type NationalIdInputConfig = {
  label: string | null;
  placeholder: string | null;
  helper: string | null;
  rules: Array<NationalIdInputRule> | null;
};
