// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provides normalized options to identify an account
 * on a network. A network may support multiple ways
 * to identify an account, and each way may require multiple
 * fields.
 */
export type NetworkIdentifier = {
  accountnumber?: string;
  routingnumber?: string;
  cardnumber?: string;
  cardexpiration?: string;
  cardcvv?: string;
  pin?: string;
  phonenumber?: string;
  email?: string;
  address?: string;
  methodid?: string;
  reference?: string;
  accountid?: string;
  qrcode?: string;
  plaid_public_token?: string;
  plaid_account_id?: string;
  plaid_institution_id?: string;
  bank_name?: string;
  plaid_mask?: string;
  plaid_account_name?: string;
  external_bank_guid?: string;
};
