// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Network =
  | "PAYY"
  | "POLYGON"
  | "ETHEREUM"
  | "SPEI"
  | "PIX"
  | "COELSA"
  | "CARD"
  | "EXTERNAL_CARD"
  | "US_BANK"
  | "PLAID";
