// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";

/**
 * A note is used in zk circuits to represent some kind of token (e.g. USDC) on
 * the Payy Network.
 *
 * This is used to create notes in the zk-rollup
 */
export type Note = {
  /**
   * The kind of note
   */
  kind: Element;
  /**
   * The contract of note
   */
  contract: Element;
  /**
   * The address of the note
   */
  address: Element;
  /**
   * The psi adds additional entropy to the note, to ensure uniqueness
   */
  psi: Element;
  /**
   * The value of the note (dependent on the token)
   */
  value: Element;
};
