// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * This type is meant to be used in client code,
 * where the actual cursor types are not needed.
 */
export type OpaqueClientCursor = {
  after: string | null;
  before: string | null;
};
