// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParseLinkOutput = {
  link: import("../ts-rs-bindings/PaymentLink").PaymentLink | null;
  error: string | null;
};
