// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParseLinkSecretOutput = {
  note: import("./Note").Note | null;
  private_key: import("./Element").Element | null;
  is_spent: boolean;
  error: string | null;
};
