// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PasswordViewModel = {
  value: string;
  /**
   * Numeric strength value: 20 | 60 | 80 | 100 | null
   */
  passwordStrength: 20 | 60 | 80 | 100 | null;
};
