// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InviteLink } from "./InviteLink";
import type { RequestLink } from "./RequestLink";
import type { SendLinkHash } from "./SendLinkHash";

/**
 * Represents any supported Payy link.
 */
export type PaymentLink =
  | { "kind": "request" } & RequestLink
  | { "kind": "send" } & SendLinkHash
  | { "kind": "invite" } & InviteLink;
