// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PayyViewModel } from "./PayyViewModel";

export type PayyCoreViewModelLongPollOutput = {
  version: number;
  viewModel: PayyViewModel;
};
