// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HomeEvent } from "./HomeEvent";
import type { PayyCoreDevEvent } from "./PayyCoreDevEvent";
import type { PayyNavigationState } from "./PayyNavigationState";

export type PayyUiEvent =
  | { "type": "Home"; "payload": HomeEvent }
  | { "type": "PayyCoreDev"; "payload": PayyCoreDevEvent }
  | { "type": "SetRoute"; "payload": { route: string } }
  | { "type": "SetNavigationStack"; "payload": { state: PayyNavigationState } };
