// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PayyNavigationState } from "./PayyNavigationState";

export type PayyNavigationRoute = {
  name: string;
  params?: Record<string, unknown> | null;
  state?: PayyNavigationState;
};
