// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HomeViewModel } from "./HomeViewModel";
import type { PayyCoreDevViewModel } from "./PayyCoreDevViewModel";
import type { PayyNavigationState } from "./PayyNavigationState";

export type PayyViewModel = {
  route: string;
  navigationState: PayyNavigationState;
  home: HomeViewModel;
  payyCoreDev: PayyCoreDevViewModel;
};
