// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";

/**
 * Public input for the points circuit
 */
export type PointsPublicInput = {
  /**
   * Value of the points
   */
  value: Element;
  /**
   * Timestamp (points proofs are valid for 1 day)
   */
  timestamp: Element;
  /**
   * Hash of address and timestamp
   */
  hash: Element;
  /**
   * Commitments to check that are in the tree and so points can be claimed
   */
  commitments: [
    Element,
    Element,
    Element,
    Element,
    Element,
    Element,
    Element,
    Element,
    Element,
    Element,
  ];
};
