// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PointsPublicInput } from "./PointsPublicInput";
import type { ProofBytes } from "./ProofBytes";

/**
 * Bundle of a proof and its public inputs for points. This can be used
 * verify the proof.
 */
export type PointsProof = {
  /**
   * Proof
   */
  proof: ProofBytes;
  /**
   * Public inputs
   */
  public_inputs: PointsPublicInput;
};
