// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Raw proof bytes for zk circuit proofs (without public inputs).
 */
export type ProofBytes = string;
