// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TermsLinkItem } from "./TermsLinkItem";

export type ProviderTermsGroup = {
  providerId: string;
  entries: Array<TermsLinkItem>;
};
