// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkIdentifier } from "./NetworkIdentifier";

/**
 * Screen-local method type (simplified from hook RampMethod)
 */
export type RampMethodListMethod = {
  localId: string | null;
  methodId: string | null;
  network: string;
  identifier: NetworkIdentifier;
};
