// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RampConfirmAction } from "./RampConfirmAction";
import type { RampConfirmQuote } from "./RampConfirmQuote";
import type { RampStaticIdentifierPreviewItem } from "./RampStaticIdentifierPreviewItem";

/**
 * ViewModel for RampConfirmScreen
 */
export type RampConfirmViewModel = {
  action: RampConfirmAction;
  actionTitle: string;
  quote: RampConfirmQuote | null;
  fromAmount: string | null;
  toAmount: string | null;
  showWarningBox: boolean;
  showUsdBanner: boolean;
  identifierPreviewItems: Array<RampStaticIdentifierPreviewItem> | null;
  errorKey: string | null;
  errorMessage: string | null;
  confirmDisabled: boolean;
  confirmLoading: boolean;
};
