// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";
import type { RampStatus } from "./RampStatus";

export type RampDepositLinkTransaction = {
  status: RampStatus;
  note_kind: Element;
};
