// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";
import type { SwapStatus } from "./SwapStatus";

export type RampSwapTransaction = {
  status: SwapStatus;
  from_note_kind: Element;
  to_note_kind: Element;
};
