// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RampStaticIdentifierAmountSummary } from "./RampStaticIdentifierAmountSummary";
import type { RampStaticIdentifierPreviewItem } from "./RampStaticIdentifierPreviewItem";

/**
 * ViewModel for RampStaticIdentifierScreen
 */
export type RampStaticIdentifierViewModel = {
  headingLines: Array<string>;
  identifierPreviewItems: Array<RampStaticIdentifierPreviewItem> | null;
  amountSummary: RampStaticIdentifierAmountSummary | null;
  minimumSourceAmountMessage: string | null;
  doneLabel: string;
};
