// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Events emitted by RampMethodCreateScreen
 */
export type RampMethodCreateEvent =
  | { "type": "onSelectGroup"; "payload": { index: number } }
  | { "type": "onFieldChange"; "payload": { field: string; value: string } }
  | {
    "type": "onFieldError";
    "payload": { index: number; error: string | null };
  }
  | { "type": "onSelectAnotherAccount"; "payload": Record<string, never> }
  | { "type": "onSubmit"; "payload": Record<string, never> }
  | { "type": "onCloseKycMismatchAlert"; "payload": Record<string, never> };
