// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RampKycReviewEvent =
  | { "type": "onDone"; "payload": Record<string, never> }
  | { "type": "onRejectedDone"; "payload": Record<string, never> }
  | { "type": "onRestartKyc"; "payload": Record<string, never> }
  | { "type": "onFixKyc"; "payload": Record<string, never> }
  | {
    "type": "onSupportPress";
    "payload": { meta: Record<string, unknown> | null };
  }
  | { "type": "onNotificationToggle"; "payload": Record<string, never> };
