// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RampMethodCreateFieldRule } from "./RampMethodCreateFieldRule";

/**
 * Field configuration for dynamic forms
 */
export type RampMethodCreateFieldConfig = {
  identifier: string;
  required: boolean;
  label: string;
  placeholder: string | null;
  rules: Array<RampMethodCreateFieldRule> | null;
};
