// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkIdentifier } from "./NetworkIdentifier";
import type { RampMethodCreateFieldConfig } from "./RampMethodCreateFieldConfig";

/**
 * ViewModel for RampMethodCreateScreen
 */
export type RampMethodCreateViewModel = {
  network: string;
  networkTitleKey: string | null;
  groupTitles: Array<string>;
  groupDescriptions: Array<string>;
  selectedGroupIndex: number;
  fields: Array<RampMethodCreateFieldConfig>;
  networkIdentifier: NetworkIdentifier;
  methodDeleted: boolean;
  isPlaid: boolean;
  hasOtherBankAccounts: boolean;
  submitDisabled: boolean;
  submitLoading: boolean;
  showKycMismatchAlert: boolean;
  showSubmitButton: boolean;
};
