// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Event variants for ramp network amount screen actions.
 */
export type RampNetworkAmountEvent = {
  "type": "onSubmit";
  "payload": Record<string, never>;
};
