// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RampMethodListItem } from "./RampMethodListItem";

/**
 * ViewModel for RampMethodListScreen
 */
export type RampMethodListViewModel = {
  methodItems: Array<RampMethodListItem>;
  loading: boolean;
  alertMessage: string | null;
  network: string;
};
