// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KycReviewStatus } from "./KycReviewStatus";
import type { KycUpdateRequired } from "./KycUpdateRequired";
import type { RampKycReviewNotificationBanner } from "./RampKycReviewNotificationBanner";
import type { RampKycSubmitStatus } from "./RampKycSubmitStatus";

export type RampKycSubmitViewModel = {
  status: RampKycSubmitStatus;
  progress: number;
  timer: number;
  reviewStatus: KycReviewStatus | null;
  updateRequired: KycUpdateRequired | null;
  notificationBanner: RampKycReviewNotificationBanner | null;
};
