// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RampBankTransferCurrency } from "./RampBankTransferCurrency";

export type RampBankTransferViewModel = {
  currencies: Array<RampBankTransferCurrency>;
  searchTerm: string;
  showSearch: boolean;
  searchPlaceholder: string;
};
