// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RampBankTransferCountry } from "./RampBankTransferCountry";

export type RampBankTransferCurrency = {
  code: string;
  name: string;
  country: RampBankTransferCountry;
};
