// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Validation rule for form fields
 */
export type RampMethodCreateFieldRule = { pattern: string; message: string };
