// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RampMethodListMethod } from "./RampMethodListMethod";
import type { RampStaticIdentifierPreviewItem } from "./RampStaticIdentifierPreviewItem";

/**
 * Method item with preview data
 */
export type RampMethodListItem = {
  method: RampMethodListMethod;
  previewItems: Array<RampStaticIdentifierPreviewItem>;
};
