// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardStatus } from "./CardStatus";
import type { Category } from "./Category";
import type { Element } from "./Element";
import type { FundingStatus } from "./FundingStatus";

export type RampCardTransaction = {
  status: CardStatus;
  name: string;
  desc: string | null;
  icon: string | null;
  category: Category;
  pending_refund_amount: Element | null;
  funding_status: FundingStatus | null;
  funding_due_amount: Element | null;
};
