// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RampBankTransferCurrency } from "./RampBankTransferCurrency";

export type RampBankTransferEvent = {
  "type": "onSearchTermChange";
  "payload": { value: string };
} | {
  "type": "onSelectCurrency";
  "payload": { currency: RampBankTransferCurrency };
};
