// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RampStaticIdentifierPreviewItemSize } from "./RampStaticIdentifierPreviewItemSize";

/**
 * Individual preview item for network identifier display
 */
export type RampStaticIdentifierPreviewItem = {
  /**
   * Key identifying the type (e.g., "accountnumber", "qrcode")
   */
  identifier: string;
  label: string;
  showLabel: boolean;
  value: string;
  size: RampStaticIdentifierPreviewItemSize;
  showCopy: boolean | null;
  copiedLabel: string | null;
};
