// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * View model for ramp network amount screen.
 */
export type RampNetworkAmountViewModel = {
  fromCurrency: string;
  toCurrency: string;
  amountDisplay: string;
  isZeroAmount: boolean;
  quoteLoading: boolean;
  quoteError: string | null;
  quoteResultDisplay: string | null;
  showBalance: boolean;
  isBalanceVisible: boolean;
  diffDisplay: string;
  overLimit: boolean;
  limitErrorMessage: string | null;
  isAmountInvalid: boolean;
  submitDisabled: boolean;
  submitLoading: boolean;
};
