// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Currency } from "./Currency";
import type { Element } from "./Element";
import type { Network } from "./Network";
import type { NetworkIdentifier } from "./NetworkIdentifier";
import type { Provider } from "./Provider";

export type RampTransactionBase = {
  id: string;
  account_id: string;
  provider: Provider;
  from_currency: Currency;
  from_amount: Element;
  from_network: Network;
  from_network_identifier: NetworkIdentifier | null;
  to_currency: Currency;
  to_amount: Element;
  to_network: Network;
  to_network_identifier: NetworkIdentifier | null;
  updated_at: string;
  added_at: string;
};
