// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KycReviewStatus } from "./KycReviewStatus";
import type { KycUpdateRequired } from "./KycUpdateRequired";
import type { LoadingResult } from "./LoadingResult";
import type { RampKycReviewNotificationBanner } from "./RampKycReviewNotificationBanner";

export type RampKycReviewViewModel = {
  status: LoadingResult<KycReviewStatus, string>;
  updateRequired: KycUpdateRequired | null;
  notificationBanner: RampKycReviewNotificationBanner | null;
};
