// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Events emitted by RampStaticIdentifierScreen
 */
export type RampStaticIdentifierEvent = {
  "type": "onDone";
  "payload": Record<string, never>;
};
