// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Events emitted by RampConfirmScreen
 */
export type RampConfirmEvent = {
  "type": "onCancel";
  "payload": Record<string, never>;
} | { "type": "onConfirm"; "payload": Record<string, never> };
