// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Action type for ramp operations
 */
export type RampConfirmAction = "deposit" | "withdraw";
