// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RampMethodListMethod } from "./RampMethodListMethod";

/**
 * Events emitted by RampMethodListScreen
 */
export type RampMethodListEvent = {
  "type": "onSelectMethod";
  "payload": { method: RampMethodListMethod };
} | { "type": "onCreateMethod"; "payload": Record<string, never> };
