// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Size options for identifier preview items
 */
export type RampStaticIdentifierPreviewItemSize = "md" | "lg";
