// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Screen-local quote (serializable subset of ramps-interface Quote)
 */
export type RampConfirmQuote = {
  id: string;
  fromCurrency: string;
  fromAmount: string;
  fromNetwork: string;
  toCurrency: string;
  toAmount: string;
  toNetwork: string;
  expiresAt: string | null;
  addedAt: string | null;
};
