// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Amount conversion summary for the ramp
 */
export type RampStaticIdentifierAmountSummary = {
  fromAmount: string;
  fromCurrency: string;
  toAmount: string;
  toCurrency: string;
};
