// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestShareEvent =
  | { "type": "onPressLinkedDone"; "payload": Record<string, never> }
  | { "type": "onPressQr"; "payload": Record<string, never> }
  | { "type": "onPressLink"; "payload": Record<string, never> }
  | { "type": "onMemoChange"; "payload": { memo: string } }
  | { "type": "onMemoErrorChange"; "payload": { hasError: boolean } };
