// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestShareViewModel = {
  /**
   * The payment amount value as a string (bigint serialization)
   */
  value: string | null;
  memoLabel: string;
  sharedLabel: string;
  containerSpacing: number;
  buttonContainerHeight: number;
  shareButtonsDisabled: boolean;
  shared: boolean;
  disableMemo: boolean;
  showNoAmountSpecifiedForZeroValue: boolean;
};
