// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";

/**
 * Request links generated by the v1 format `/r/1/<value>/<memo?>#<public_key>/<invite_code?>`.
 */
export type RequestLink = {
  value: Element;
  public_key: Element;
  invite_code: string | null;
  memo: string | null;
};
