// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestAmountEvent = {
  "type": "onValueChange";
  "payload": { value: string };
} | { "type": "onSubmit"; "payload": Record<string, never> };
