// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RewardsTaskViewModel = {
  id: string;
  title: string;
  desc: string | null;
  points: string;
  pointsLabel: string;
  earned: string | null;
  earnedLabel: string | null;
  btnTitle: string | null;
  persisted: boolean | null;
  disabled: boolean | null;
  depositMore: boolean | null;
  hasAction: boolean;
  hasDepositMoreAction: boolean;
};
