// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RewardsCodeEvent =
  | { "type": "onChange"; "payload": { code: string } }
  | { "type": "onSubmit"; "payload": Record<string, never> }
  | { "type": "onPaste"; "payload": Record<string, never> };
