// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RewardsTaskViewModel } from "./RewardsTaskViewModel";

export type RewardsViewModel = {
  loading: boolean;
  totalPoints: number;
  tasks: Array<RewardsTaskViewModel>;
};
