// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectTokenOptionViewModel } from "./SelectTokenOptionViewModel";

export type SelectTokenViewModel = {
  heading: string;
  tokens: Array<SelectTokenOptionViewModel>;
};
