// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectTokenId } from "./SelectTokenId";

export type SelectTokenOptionViewModel = { id: SelectTokenId; label: string };
