// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectTokenId } from "./SelectTokenId";

export type SelectTokenEvent = {
  "type": "onTokenPress";
  "payload": { tokenId: SelectTokenId };
};
