// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Event variants for send amount screen actions.
 */
export type SendAmountEvent = {
  "type": "onValueChange";
  "payload": { value: string };
} | { "type": "onNext"; "payload": Record<string, never> };
