// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Empty event enum for standardized screen contract.
 * This screen has no user interactions, but we include the enum
 * to maintain consistency with other screens.
 */
export type SendQREvent = never;
