// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SendAmountViewModel = {
  value: string;
  /**
   * Balance as string to support bigint serialization (null if not loaded).
   */
  balance: string | null;
  isBalanceVisible: boolean;
  isBalanceLoading: boolean;
  marginTop: number;
  nextLabel: string;
  nextDisabled: boolean;
  showNextButton: boolean;
};
