// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";

export type SendRegistryInput = {
  value: Element;
  memo?: string | null;
  to_public_key: Element;
};
