// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SendShareViewModel = {
  /**
   * The payment amount value as a string (bigint serialization)
   */
  value: string;
  memoLabel: string;
  shareAgainLabel: string;
  doneLabel: string;
  loadingLabel: string | null;
  shareButtonsDisabled: boolean;
  shareLoading: boolean;
  shareResultReady: boolean;
  shareAgainVisible: boolean;
  shareAgainDisabled: boolean | null;
  showShareWarning: boolean;
  shareWarningMessages: Array<string>;
  disableMemo: boolean | null;
  showNoAmountSpecifiedForZeroValue: boolean | null;
};
