// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkStatusExternal } from "./LinkStatusExternal";

export type SendLinkExternal = {
  /**
   * Link string
   */
  link: string;
  /**
   * Link status
   */
  link_status: LinkStatusExternal;
  /**
   * Memo (optional)
   */
  memo: string | null;
};
