// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `/s/<memo?>#<secret>` links containing a base58-encoded payload.
 */
export type SendLinkHash = { secret_hash: string; memo: string | null };
