// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SendLinkHash } from "./SendLinkHash";

/**
 * Convenience enum for send-only link parsing operations.
 */
export type SendLink = { "kind": "send" } & SendLinkHash;
