// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingsScreenItemKey } from "./SettingsScreenItemKey";

export type SettingsScreenEvent = {
  "type": "onItemPress";
  "payload": { key: SettingsScreenItemKey };
};
