// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingsScreenItem } from "./SettingsScreenItem";

export type SettingsScreenViewModel = {
  items: Array<SettingsScreenItem>;
  showVersion: boolean;
  versionLabel: string;
};
