// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingsScreenItemKey =
  | "backup"
  | "recoverWallet"
  | "advanced"
  | "stickers"
  | "faq"
  | "community"
  | "help";
