// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingsScreenItemKey } from "./SettingsScreenItemKey";

export type SettingsScreenItem = {
  key: SettingsScreenItemKey;
  title: string;
  secondary: string | null;
};
