// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";

/**
 * A signed 256-bit integer that wraps an `Element` with a sign bit
 *
 * This type allows performing arithmetic operations with signed numbers,
 * while the underlying `Element` remains unsigned.
 */
export type SignedElement = {
  /**
   * The absolute value stored as an Element
   */
  value: Element;
  /**
   * The sign: true for negative, false for positive or zero
   */
  negative: boolean;
};
