// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SnarkWitnessV1 } from "./SnarkWitnessV1";

export type SnarkWitness = { V1: SnarkWitnessV1 };
