// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";
import type { WalletDataNote } from "./WalletDataNote";

export type StoredNote = {
  note: WalletDataNote;
  commitment: Element;
  timestamp?: number;
  received?: number;
  spent?: number;
  owner?: Element;
  remote?: boolean;
  private_key?: Element;
  invalidreason?: string;
};
