// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SupportIssuesListEvent =
  | { "type": "onRefresh"; "payload": Record<string, never> }
  | { "type": "onNewChat"; "payload": Record<string, never> }
  | { "type": "onNewChatDisabledPress"; "payload": Record<string, never> }
  | { "type": "onOpenIssue"; "payload": { issueId: string } };
