// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SupportChatDraftAttachment = {
  uri: string;
  filename: string;
  contentType: string;
  width: number | null;
  height: number | null;
};
