// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SupportIssue } from "./SupportIssue";

export type SupportIssuesListViewModel = {
  issues: Array<SupportIssue>;
  showLoader: boolean;
  remoteHasLoaded: boolean;
  isNewChatDisabled: boolean;
};
