// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";
import type { SupportChatAttachment } from "./SupportChatAttachment";

export type SupportChatMessageItem = {
  id: string;
  role: Role;
  isBot: boolean;
  message: string;
  attachment: SupportChatAttachment | null;
  localOnly: boolean;
  addedAt: string;
};
