// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SupportChatDraftAttachment } from "./SupportChatDraftAttachment";
import type { SupportChatMessageItem } from "./SupportChatMessageItem";
import type { SupportChatNotificationBanner } from "./SupportChatNotificationBanner";

export type SupportChatViewModel = {
  messages: Array<SupportChatMessageItem>;
  updateDisabled: boolean;
  message: string;
  draftAttachment: SupportChatDraftAttachment | null;
  isSending: boolean;
  isSendDisabled: boolean;
  notificationBanner: SupportChatNotificationBanner | null;
};
