// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

export type SupportMessage = {
  id: string;
  support_issue_id: string;
  external_id: string;
  emoji: string | null;
  role: Role;
  message: string;
  attachment: {};
  added_at: string;
  is_bot: boolean;
  is_internal: boolean;
  agent_id: number | null;
};
