// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";

export type SupportIssue = {
  id: string;
  wallet_id: string;
  external_id: string;
  status: Status;
  channel: string;
  subject: string | null;
  unread_count: number;
  last_message: string;
  last_message_at: string;
  last_read_at: string | null;
  closed_at: string | null;
  updated_at: string;
  added_at: string;
  metadata: unknown | null;
  auto_close_at: string | null;
  auto_close_minutes: number | null;
  last_ai_support_bot_processed_at: string | null;
};
