// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SupportChatEvent =
  | { "type": "onMessageChange"; "payload": { value: string } }
  | { "type": "onSend"; "payload": Record<string, never> }
  | { "type": "onAddAttachmentPress"; "payload": Record<string, never> }
  | { "type": "onLinkPress"; "payload": { url: string } }
  | { "type": "onNotificationToggle"; "payload": Record<string, never> };
