// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SupportChatAttachment = {
  filename: string;
  contentType: string;
  width: number | null;
  height: number | null;
  /**
   * Base64 content only for inline/local attachments.
   */
  content: string | null;
};
