// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderTermsGroup } from "./ProviderTermsGroup";
import type { TermsLinkItem } from "./TermsLinkItem";

export type TermsViewModel = {
  providerTerms: Array<ProviderTermsGroup>;
  appTerms: Array<TermsLinkItem>;
};
