// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UtxoProof } from "./UtxoProof";

/**
 * Request for submit transaction
 */
export type TransactionRequest = {
  /**
   * Utxo proof to be verified and applied
   */
  proof: UtxoProof;
};
