// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockHeight } from "./BlockHeight";
import type { Element } from "./Element";

/**
 * Response for submit transaction
 */
export type TransactionResponse = {
  /**
   * Height of the block the transaction was included in
   */
  height: BlockHeight;
  /**
   * Root hash of the merkle tree for the block
   */
  root_hash: Element;
  /**
   * Transaction hash of submitted transaction
   */
  txn_hash: Element;
};
