// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";
import type { TreasurySwapDirection } from "./TreasurySwapDirection";

export type TreasurySwapInput = {
  amount: Element;
  direction: TreasurySwapDirection;
};
