// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockHeight } from "./BlockHeight";
import type { Element } from "./Element";
import type { UtxoProof } from "./UtxoProof";

/**
 * Transaction data with additional metadata.
 */
export type TxnWithInfo = {
  /**
   * Transaction proof.
   */
  proof: UtxoProof;
  /**
   * Hash of the transaction.
   */
  hash: Element;
  /**
   * Index of the transaction inside the block.
   */
  index_in_block: bigint;
  /**
   * Height of the block that included the transaction.
   */
  block_height: BlockHeight;
  /**
   * Timestamp assigned to the transaction.
   */
  time: bigint;
};
