// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The public input for a Utxo transaction
 */
export type UtxoPublicInput = {
  /**
   * The input commitments
   */
  input_commitments: [string, string];
  /**
   * The output commitments
   */
  output_commitments: [string, string];
  /**
   * The message of the transaction
   */
  messages: [string, string, string, string, string];
};
