// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of Utxo transaction
 */
export type UtxoKind = "NULL" | "SEND" | "MINT" | "BURN";
