// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UtxoPublicInput } from "./UtxoPublicInput";

/**
 * The output proof for a Utxo transaction
 */
export type UtxoProof = {
  /**
   * The proof for the Utxo transaction
   */
  proof: string;
  /**
   * The public input for the Utxo transaction
   */
  public_inputs: UtxoPublicInput;
};
