// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VerifyCodeEvent =
  | { "type": "onSubmit"; "payload": { code: string } }
  | { "type": "onResend"; "payload": Record<string, never> }
  | { "type": "onEditPhone"; "payload": Record<string, never> };
