// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Events emitted by the WalletRecoveryScreen
 */
export type WalletRecoveryEvent = {
  "type": "onMnemonicChange";
  "payload": { value: string };
} | { "type": "onRecover"; "payload": Record<string, never> };
