// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";

export type WalletDataNote = {
  address: Element;
  psi: Element;
  value: Element;
  source: Element | null;
  token: string | null;
};
