// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChainConfig } from "./ChainConfig";

export type WalletMobileConfig = {
  guild_rpc_url: string;
  node_rpc_url: string;
  social_recovery_contract_address: string;
  primary_rollup_chain_id: number;
  minimum_gas_price_gwei: bigint | null;
  dev: boolean;
  data_dir?: string;
  chains: { [key in number]?: ChainConfig };
};
