// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadingResult } from "./LoadingResult";
import type { WalletCardBanner } from "./WalletCardBanner";

export type WalletViewModel = {
  isBalanceVisible: boolean;
  showMigrationMessage: boolean;
  showBackupCallout: boolean;
  backupTitle: string;
  /**
   * Balance as LoadingResult with optional atomic micro-unit amount as decimal string (bigint-safe in TS).
   * None represents unknown/uninitialized balance, preserving Send/Deposit label semantics.
   */
  balance: LoadingResult<string | null, string>;
  depositPendingBalance: LoadingResult<string | null, string>;
  unclaimedLinksBalance: LoadingResult<string | null, string>;
  cardBanner: WalletCardBanner;
};
