// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Events emitted by the WalletBackupScreen
 */
export type WalletBackupEvent = {
  "type": "onDownloadRecoveryPhrase";
  "payload": Record<string, never>;
} | { "type": "onGuardianBackupPress"; "payload": Record<string, never> };
