// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadingResult } from "./LoadingResult";

export type WalletYieldBanner =
  | { "type": "hidden"; "payload": Record<string, never> }
  | { "type": "cta"; "payload": Record<string, never> }
  | {
    "type": "balance";
    "payload": { value: LoadingResult<string | null, string> };
  };
