// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";

/**
 * The kind of private key used for the note
 */
export type WalletPrivateKeyKind =
  | { "kind": "PROVIDED"; "data": Element }
  | { "kind": "WALLET" }
  | { "kind": "DERIVED"; "data": Array<number> }
  | { "kind": "PADDING" }
  | { "kind": "EXTERNAL_NO_PRIVATE_KEY" };
