// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ViewModel for the WalletRecoveryScreen
 */
export type WalletRecoveryViewModel = {
  mnemonic: string;
  recovering: boolean;
  errorMessage: string | null;
  balanceNotice: string | null;
};
