// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Note } from "./Note";
import type { WalletPrivateKeyKind } from "./WalletPrivateKeyKind";

/**
 * For the wallet, we use a wrapper struct around Note, as this may be
 * serialized and stored and we don't want to store the private key. The private key
 * may be derived differntly depending on how its generated.
 */
export type WalletNote = {
  note: Note;
  private_key: WalletPrivateKeyKind;
  added_at: string;
  updated_at: string;
};
