// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ViewModel for the WalletBackupScreen
 */
export type WalletBackupViewModel = {
  backupWarning: boolean;
  hasTappedDownloadRecoveryPhrase: boolean;
  isGuardianBackupEnabled: boolean;
  backupDescription: string;
  backupSecondaryDescription: string;
  optionsTitle: string;
  seedPhraseWarning: string;
  seedPhraseOptionHeading: string;
  seedPhraseOptionDescription: string;
  socialRecoveryHeading: string;
  socialRecoveryDescription: string;
  systemBackupHeading: string;
  systemBackupDescription: string;
};
