// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KycStatus } from "./KycStatus";

export type WalletCardBanner =
  | { "type": "none"; "payload": Record<string, never> }
  | { "type": "promo"; "payload": { title: string; subtitle: string } }
  | {
    "type": "countdown";
    "payload": {
      status: KycStatus;
      /**
       * Unix epoch timestamp in milliseconds (JS Date.now() compatible).
       */
      addedAt: number;
      showCountdown: boolean;
    };
  }
  | { "type": "pending"; "payload": Record<string, never> }
  | { "type": "active"; "payload": { last4: string } }
  | { "type": "frozen"; "payload": { last4: string } };
