// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WalletNote } from "./WalletNote";

/**
 * A set of notes, prevents duplicats from being added. Similar to a Vec but the order
 * of notes in the set is not guarenteed.
 */
export type WalletNoteSet = Array<WalletNote>;
