// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WalletEvent =
  | { "type": "onToggleBalance"; "payload": Record<string, never> }
  | { "type": "onPendingDepositPress"; "payload": Record<string, never> }
  | { "type": "onUnclaimedPress"; "payload": Record<string, never> }
  | { "type": "onBackupPress"; "payload": Record<string, never> }
  | { "type": "onSendPress"; "payload": Record<string, never> }
  | { "type": "onRequestPress"; "payload": Record<string, never> }
  | { "type": "onCardBannerPress"; "payload": Record<string, never> };
