// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WithdrawOptionGroupViewModel } from "./WithdrawOptionGroupViewModel";

export type WithdrawViewModel = {
  optionGroups: Array<WithdrawOptionGroupViewModel>;
};
