// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WithdrawWalletViewModel = {
  chainKey: string;
  chainName: string;
  chainIconFallbackUri: string | null;
  showMainChainEta: boolean;
  address: string;
  amount: string;
  shouldShowBalanceRemaining: boolean;
  balanceDiff: string;
  balanceOverLimit: boolean;
  isBalanceVisible: boolean;
  isBalanceLoading: boolean;
  submitButtonVisible: boolean;
  submitButtonEnabled: boolean;
  submitAmountLabel: string | null;
  isFormValid: boolean;
};
