// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WithdrawOptionItemViewModel } from "./WithdrawOptionItemViewModel";

/**
 * Group of withdraw options
 */
export type WithdrawOptionGroupViewModel = {
  title: string;
  subtitle: string | null;
  options: Array<WithdrawOptionItemViewModel>;
};
