// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WithdrawWalletEvent =
  | { "type": "onAddressChange"; "payload": { value: string } }
  | { "type": "onPasteAddress"; "payload": Record<string, never> }
  | { "type": "onAmountChange"; "payload": { value: string } }
  | { "type": "onSubmit"; "payload": Record<string, never> };
