// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Event variants for withdraw screen actions
 */
export type WithdrawEvent = {
  "type": "onBankTransferPress";
  "payload": Record<string, never>;
} | { "type": "onCryptoPress"; "payload": { chainKey: string } };
