// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WithdrawEvent } from "./WithdrawEvent";

/**
 * Individual withdraw option item (without callbacks or non-serializable types)
 * Note: Only include enabled/visible options in the ViewModel - disabled options are hidden, not shown disabled
 * Each option embeds its event directly for type-safe dispatch
 */
export type WithdrawOptionItemViewModel = {
  title: string;
  description: string | null;
  iconId: string;
  comingSoon: boolean;
  event: WithdrawEvent;
};
