// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { BurnVerifierV2$Type } from "./BurnVerifierV2";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BurnVerifierV2"]: BurnVerifierV2$Type;
    ["contracts/BurnVerifierV2.sol:BurnVerifierV2"]: BurnVerifierV2$Type;
  }
}
